updated for ros2 jazzy

diff --git a/Dockerfile_interactive b/Dockerfile_interactive
--- a/Dockerfile_interactive
+++ b/Dockerfile_interactive
@@ -1,12 +1,13 @@
-FROM awesomebytes/pepper_2.5.5.5
+ARG BASE_IMAGE=awesomebytes/pepper_2.5.5.5
+FROM ${BASE_IMAGE}
 
 USER nao
 WORKDIR /home/nao
 
-#Loading the ros2-prepared archive
-COPY gentoo_prefix_base.tar.lzma  ./gentoo_prefix_base.tar.lzma
-RUN tar --lzma -xvf gentoo_prefix_base.tar.lzma &&\
-    rm gentoo_prefix_base.tar.lzma
+# Loading the base prefix archive
+COPY --chown=nao:nao gentoo_prefix_base.tar.lzma ./gentoo_prefix_base.tar.lzma
+RUN (tar -J -xf gentoo_prefix_base.tar.lzma 2>/dev/null || tar --lzma -xf gentoo_prefix_base.tar.lzma 2>/dev/null || tar -xf gentoo_prefix_base.tar.lzma) && \
+    rm -f gentoo_prefix_base.tar.lzma
 
 # Fix permissions of tmp
 USER root
@@ -14,193 +15,121 @@ RUN chmod a=rwx,o+t /tmp
 USER nao
 
 # Prepare environment to run everything in the prefixed shell
-RUN cd /tmp && ln -s /home/nao/gentoo gentoo &&\
-    cp /etc/group /tmp/gentoo/etc/group || true &&\
+RUN cd /tmp && ln -sf /home/nao/gentoo gentoo && \
+    cp /etc/group /tmp/gentoo/etc/group || true && \
     cp /etc/passwd /tmp/gentoo/etc/passwd || true
-# # To make sure everything builds and reports i686 we do this trick
-# RUN sed -i 's/env -i/linux32 env -i/' /tmp/gentoo/executeonprefix
+
 # To allow the use of the $EPREFIX variable
 RUN sed -i 's/SHELL=$SHELL"/SHELL=$SHELL EPREFIX=$EPREFIX"/' /tmp/gentoo/executeonprefix
 
-# And now switch the shell so every RUN command is executed in it
+# Switch shell so subsequent RUN commands execute inside prefix
 SHELL ["/tmp/gentoo/executeonprefix"]
 
-# Let's make the compilations faster when possible
-# Substitute the default -j2 with -j<NUM_CORES/2>
-RUN sed -i -e 's/j1/j'"$((`grep -c \^processor \/proc\/cpuinfo` / 2))"'/g' $EPREFIX/etc/portage/make.conf
-# Add extra jobs if we have enough CPUs
-RUN sed -i 's/EMERGE_DEFAULT_OPTS=.*//' $EPREFIX/etc/portage/make.conf &&\
+# Configure compilation parallelism based on host cores
+RUN sed -i -e 's/j1/j'"$((`grep -c \^processor \/proc\/cpuinfo` / 2))"'/g' $EPREFIX/etc/portage/make.conf 2>/dev/null || true
+RUN sed -i 's/EMERGE_DEFAULT_OPTS=.*//' $EPREFIX/etc/portage/make.conf 2>/dev/null || true && \
     echo "EMERGE_DEFAULT_OPTS=\"--jobs $((`grep -c \^processor \/proc\/cpuinfo` / 2)) --load-average `grep -c \^processor \/proc\/cpuinfo`\"" >> $EPREFIX/etc/portage/make.conf
 
-# remove python3.12
-RUN emerge --unmerge python:3.12
-RUN emerge --depclean
-RUN rm -rf /tmp/gentoo/usr/bin/python3.12 /tmp/gentoo/usr/bin/python3.12-config
+# Clean up any conflicting python3.12 binaries
+RUN rm -rf /tmp/gentoo/usr/bin/python3.12 /tmp/gentoo/usr/bin/python3.12-config 2>/dev/null || true
 
-#install onnxruntime from wheel
-ADD wheels/onnxruntime-1.15.1-cp311-cp311-linux_i686.whl /tmp/gentoo/onnxruntime-1.15.1-cp311-cp311-linux_i686.whl
-RUN pip install /tmp/gentoo/onnxruntime-1.15.1-cp311-cp311-linux_i686.whl && rm /tmp/gentoo/onnxruntime-1.15.1-cp311-cp311-linux_i686.whl
+# Clean up any old ROS 1 / Humble workspaces if present from base archive
+RUN rm -rf /home/nao/ros2_humble /home/nao/catkin_ros2 2>/dev/null || true
 
-RUN mkdir -p /home/nao/.local &&\
-    cd /home/nao/.local &&\
-    git clone https://github.com/aldebaran/qibuild.git && \
-    cd qibuild && \
-    python -m pip install -e . 
+# Purge any heavy AI packages from base image to keep image lean and fast
+RUN pip uninstall -y onnxruntime tflite_runtime spacy transformers torch vosk kaldi 2>/dev/null || true
+RUN rm -rf /home/nao/.local/kaldi /home/nao/.local/vosk-api 2>/dev/null || true
 
-RUN mkdir -p /home/nao/.local &&\
-    cd /home/nao/.local &&\
-    git clone https://github.com/aldebaran/libqi.git -b qi-framework-v3.0.0 && \
-    cd libqi && \
-    mkdir build && cd build && \
-    cmake .. -DQI_WITH_TESTS=OFF -DCMAKE_PREFIX_PATH=/home/nao/.local/qibuild/cmake/qibuild -DCMAKE_INSTALL_PREFIX=/tmp/gentoo/usr -DCMAKE_CXX_FLAGS='-std=c++17' && \
-    make -j12 && \
-    make install
+# Install qibuild if not already present
+RUN if [ ! -d /home/nao/.local/qibuild ]; then \
+        mkdir -p /home/nao/.local && \
+        cd /home/nao/.local && \
+        git clone https://github.com/aldebaran/qibuild.git && \
+        cd qibuild && \
+        python -m pip install -e . ; \
+    fi
 
-# RUN mkdir -p /home/nao/.local &&\
-#     cd /home/nao/.local &&\
-#     git clone https://github.com/victorpaleologue/libqi-python.git && cd libqi-python && \
-#     BOOST_VERSION=1.78 PYBIND11_VERSION=2.11.1 python setup.py bdist_wheel -DQI_WITH_TESTS=OFF -Dqi_DIR=/home/nao/.local/libqi/build/sdk/cmake -Dqibuild_DIR=/home/nao/.local/qibuild/cmake/qibuild && \
-#     pip install dist/*.whl
+# Build and install libqi (C++17) if not already installed
+RUN if [ ! -f /tmp/gentoo/usr/lib/libqi.so ]; then \
+        mkdir -p /home/nao/.local && \
+        cd /home/nao/.local && \
+        git clone https://github.com/aldebaran/libqi.git -b qi-framework-v3.0.0 && \
+        cd libqi && \
+        mkdir -p build && cd build && \
+        cmake .. -DQI_WITH_TESTS=OFF -DCMAKE_PREFIX_PATH=/home/nao/.local/qibuild/cmake/qibuild -DCMAKE_INSTALL_PREFIX=/tmp/gentoo/usr -DCMAKE_CXX_FLAGS='-std=c++17' && \
+        make -j$((`grep -c \^processor \/proc\/cpuinfo` / 2 + 1)) && \
+        make install ; \
+    fi
 
-#install libqi-python from wheel
+# Install libqi-python from wheel
 ADD wheels/qi-3.1.0-cp311-cp311-linux_i686.whl /tmp/gentoo/qi-3.1.0-cp311-cp311-linux_i686.whl
-RUN pip install /tmp/gentoo/qi-3.1.0-cp311-cp311-linux_i686.whl && rm /tmp/gentoo/qi-3.1.0-cp311-cp311-linux_i686.whl
+RUN pip install /tmp/gentoo/qi-3.1.0-cp311-cp311-linux_i686.whl && rm -f /tmp/gentoo/qi-3.1.0-cp311-cp311-linux_i686.whl
 
-RUN cd /home/nao/.local && \
-    git clone -b vosk --single-branch https://github.com/alphacep/kaldi \
-    && cd /home/nao/.local/kaldi/tools \
-    && git clone -b v0.3.13 --single-branch https://github.com/xianyi/OpenBLAS \
-    && git clone -b v3.2.1  --single-branch https://github.com/alphacep/clapack \
-    && make -C OpenBLAS OPENBLAS_TARGET=ATOM TARGET=ATOM ONLY_CBLAS=1 DYNAMIC_ARCH=1 USE_LOCKING=1 USE_THREAD=0 all \
-    && make -C OpenBLAS PREFIX=/home/nao/.local/kaldi/tools/OpenBLAS/install install \
-    && mkdir -p clapack/BUILD && cd clapack/BUILD && cmake .. && make -j 8 || true 
-RUN cd /home/nao/.local/kaldi/tools/clapack/BUILD \
-    && find . -name "*.a" | xargs cp -t ../../OpenBLAS/install/lib \
-    && cd /home/nao/.local/kaldi/tools \
-    && git clone --single-branch https://github.com/alphacep/openfst openfst \
-    && cd openfst \
-    && autoreconf -i \
-    && CFLAGS="-g -O3" CXXFLAGS="-msse -mfpmath=sse" ./configure --prefix=/home/nao/.local/kaldi/tools/openfst --enable-static --enable-shared --enable-far --enable-ngram-fsts --enable-lookahead-fsts --with-pic --disable-bin \
-    && make -j 10 && make install \
-    && cd /home/nao/.local/kaldi/src \
-    && ./configure --mathlib=OPENBLAS_CLAPACK --shared --use-cuda=no \
-    && sed -i 's:-msse -msse2:-msse -msse2:g' kaldi.mk \
-    && sed -i 's: -O1 : -O3 :g' kaldi.mk \
-    && make -j $(nproc) online2 lm rnnlm \
-    && find /home/nao/.local/kaldi -name "*.o" -exec rm {} \;
-    
-# dependencies for vosk
-RUN pip install tqdm cffi requests srt
-RUN cd /home/nao/.local && \
-    git clone https://github.com/alphacep/vosk-api \
-    && cd vosk-api/src \
-    && KALDI_ROOT=/home/nao/.local/kaldi make -j8 \
-    && cd ../python \
-    && python setup.py install
+# Install psutil and tornado required by ros2cli and rosbridge_server
+ADD wheels/psutil-7.1.1-cp36-abi3-manylinux_2_12_i686.manylinux2010_i686.manylinux_2_17_i686.manylinux2014_i686.whl /tmp/gentoo/psutil.whl
+ADD wheels/tornado-6.5.4-cp39-abi3-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl /tmp/gentoo/tornado.whl
+RUN pip install /tmp/gentoo/psutil.whl /tmp/gentoo/tornado.whl && rm -f /tmp/gentoo/psutil.whl /tmp/gentoo/tornado.whl
 
-RUN emerge sci-libs/orocos_kdl
+# Ensure core scientific/kinematic library orocos_kdl and media dependencies (ffmpeg, gstreamer, tmux, tree) are present
+RUN emerge sci-libs/orocos_kdl media-libs/dav1d media-video/ffmpeg app-misc/tmux app-text/tree \
+           media-libs/gstreamer media-libs/gst-plugins-base media-libs/gst-plugins-good \
+           media-plugins/gst-plugins-jpeg media-plugins/gst-plugins-v4l2 dev-vcs/git-lfs 2>/dev/null || true
 
-### THIS IS THE BUILD OF ONNXRUNTIME FROM SOURCE - NOT NEEDED ANYMORE
-# Need to compile pybind11 from source to fight the redefinition of PyFrameObject:
-# https://github.com/sirfz/tesserocr/issues/298
-RUN cd ~/.local && git clone https://github.com/pybind/pybind11.git -b v2.10.0 &&  cd pybind11 && \
-    mkdir build && \
-    cd build && \
-    cmake .. -DPYBIND11_PYTHON_VERSION=3.11 -DCMAKE_INSTALL_PREFIX=/tmp/gentoo/usr && \
-    make -j12 && \
-    make install
+# Download and compile ROS 2 Jazzy Jalisco
+RUN mkdir -p ~/ros2_jazzy/src && \
+    cd ~/ros2_jazzy && \
+    vcs import --input https://raw.githubusercontent.com/ros2/ros2/jazzy/ros2.repos src && \
+    # Remove unneeded packages (CycloneDDS, Iceoryx, GUI tools, visualization, tests, and non-32-bit packages)
+    rm -rf src/eclipse-cyclonedds src/eclipse-iceoryx src/ros-visualization src/ros2/rviz \
+           src/ros/ros_tutorials/turtlesim src/ros2/geometry2/tf2_bullet src/ros2/geometry2/test_tf2 \
+           src/ros2/mimick_vendor src/ros2/ros2_tracing/lttngpy src/ros2-rust \
+           src/ros2/demos src/ros2/examples src/ros2/system_tests src/ros2/performance_test_fixture \
+           src/ros2/rmw_cyclonedds src/ros2/rmw_connextdds src/ros2/tlsf \
+           src/gazebo-release src/ros2/orocos_kdl_vendor/python_orocos_kdl_vendor \
+           src/ros2/realtime_support && \
+    cd src && git clone https://github.com/ptrmu/ros2_shared.git 2>/dev/null || true && cd .. && \
+    colcon build --symlink-install --cmake-args \
+        -DBUILD_TESTING=OFF \
+        -DTRACETOOLS_DISABLED=ON \
+        -DTRACETOOLS_STATUS_CHECKING_TOOL=OFF \
+        -DLTTNGPY_DISABLED=ON
 
-# ONNX won't install protoc correctly by default so we do it beforehand
-# RUN cd ~/.local && wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_32.zip && \
-#     unzip -o protoc-21.12-linux-x86_32.zip -d /tmp/gentoo/usr/local/ bin/protoc && \
-#     unzip -o protoc-21.12-linux-x86_32.zip -d /tmp/gentoo/usr/local/ 'include/*' && \
-#     ldconfig && \
-#     rm protoc-21.12-linux-x86_32.zip
+# Download and build naoqi_driver2, rosbridge_suite (WebSocket), and web_video_server (HTTP video stream)
+RUN . ~/ros2_jazzy/install/local_setup.bash && \
+    mkdir -p ~/catkin_ros2/src && \
+    cd ~/catkin_ros2/src/ && \
+    git clone https://github.com/ros-naoqi/naoqi_driver2.git && \
+    git clone --branch rolling https://github.com/ros-perception/vision_opencv && \
+    git clone --branch release/jazzy/naoqi_libqi https://github.com/ros-naoqi/libqi-release && \
+    git clone --branch release/jazzy/naoqi_libqicore https://github.com/ros-naoqi/libqicore-release && \
+    git clone https://github.com/ros-naoqi/naoqi_bridge_msgs2 && \
+    git clone --branch ros2-jazzy https://github.com/ros/diagnostics && \
+    git clone --branch jazzy https://github.com/RobotWebTools/rosbridge_suite.git && \
+    git clone --branch ros2-develop https://github.com/fkie/async_web_server_cpp.git && \
+    git clone --branch ros2 https://github.com/RobotWebTools/web_video_server.git && \
+    cd .. && colcon build --symlink-install --cmake-args -DBUILD_TESTING=OFF
 
-# build latest onnxruntime version
-# RUN cd .local && git clone --recursive https://github.com/Microsoft/onnxruntime.git -b v1.15.1 && \
-#     cd onnxruntime && \ 
-#     ./build.sh --config Release --parallel --build_wheel --disable_ml_ops --update --build --x86 --cmake_extra_defines CMAKE_INSTALL_PREFIX=/tmp/gentoo/usr CMAKE_CXX_FLAGS="-lstdc++ -msse -msse4.1 -mfpmath=sse" CMAKE_SYSTEM_NAME=Linux CMAKE_SYSTEM_PROCESSOR=i686 ONNX_CUSTOM_PROTOC_EXECUTABLE=/tmp/gentoo/usr/local/bin/protoc && \
-#     cd build/Linux/Release/ && \
-#     make install && \
-#     cd dist && pip install *.whl
+# Git config to avoid SSL verification on robots with unsynced RTC clocks
+RUN git config --global http.sslVerify false
 
-#Download ROS2
-RUN mkdir -p ~/ros2_humble/src &&\
-    cd ~/ros2_humble &&\
-    vcs import --input https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos src &&\
-    #Remove unecessary packages (Unusable display and DDS implementations that do not work on 32 bits OS)
-    rm -rf src/eclipse-cyclonedds src/eclipse-iceoryx src/ros-visualization src/ros2/rviz src/ros/ros_tutorials/turtlesim src/ros2/geometry2/tf2_bullet src/ros2/geometry2/test_tf2 &&\
-    cd src && git clone https://github.com/ptrmu/ros2_shared.git && cd .. &&\
-    #Build ROS2
-    colcon build --symlink-install; exit 0
-
-RUN cd ~/ros2_humble/ &&\
-    #Building will fail due to the mimick package. While compiling mimick downloads and builds mimick_vendor. The CMakeList.txt of mimick_vendor doesn't take into account 32 bits architecture like Pepper and has to be adjusted accordingly.   
-    sed -i '61s/.*/  set (_ARCH "x86")/' ~/ros2_humble/build/mimick_vendor/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7-prefix/src/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7/CMakeLists.txt &&\
-    colcon build --symlink-install
-
-# #Download and build naoqi_driver2
-# we build without tests because otherwise libqi-release will fail and I'm too lazy to fix it (related to Gtest not allowing c++14 anymore)
-RUN . ~/ros2_humble/install/local_setup.bash &&\
-    mkdir -p ~/catkin_ros2/src &&\
-    cd ~/catkin_ros2/src/ &&\
-    git clone https://github.com/Maelic/naoqi_driver2.git -b patch-1 &&\
-    git clone --branch humble https://github.com/ros-perception/vision_opencv &&\  
-    git clone --branch release/humble/naoqi_libqi https://github.com/ros-naoqi/libqi-release &&\
-    git clone --branch release/humble/naoqi_libqicore https://github.com/ros-naoqi/libqicore-release &&\             
-    git clone https://github.com/ros-naoqi/naoqi_bridge_msgs2 &&\
-    git clone https://github.com/ros/diagnostics && \
-    cd .. && colcon build --symlink-install  --cmake-args -DBUILD_TESTING=OFF
-
-
-# RUN  cmake -DCMAKE_BUILD_TYPE=Release -DTREAT_WARNING_AS_ERROR=OFF -DENABLE_AVX512F=OFF -DBUILD_SHARED_LIBS=OFF -DENABLE_PYTHON=ON -DENABLE_INTEL_GNA=OFF -DENABLE_IR_V7_READER=OFF -DENABLE_GAPI_PREPROCESSING=OFF -DENABLE_ONEDNN_FOR_GPU=OFF -DENABLE_INTEL_GPU=OFF -DENABLE_OV_PADDLE_FRONTEND=OFF -DENABLE_OV_IR_FRONTEND=OFF -DENABLE_INTEL_CPU=OFF -DENABLE_WHEEL=ON -DENABLE_OV_TF_FRONTEND=OFF -DENABLE_TBB_RELEASE_ONLY=OFF -DENABLE_INTEL_MYRIAD=OFF -DTHREADING=SEQ -DENABLE_OV_ONNX_FRONTEND=OFF ..
-
-RUN BLIS_ARCH="generic" pip install transformers spacy
-# for wathever reason the wheel is not working
-# ADD wheels/spacy-3.7.4-cp311-cp311-linux_i686.whl /tmp/gentoo/spacy-3.7.4-cp311-cp311-linux_i686.whl
-# RUN pip install /tmp/gentoo/spacy-3.7.4-cp311-cp311-linux_i686.whl --no-binary blis && rm /tmp/gentoo/spacy-3.7.4-cp311-cp311-linux_i686.whl
-RUN python3.11 -m spacy download en_core_web_sm
-
-RUN emerge dev-vcs/git-lfs
-
-# for GStreamer
-RUN emerge media-libs/gstreamer media-libs/gst-plugins-base media-libs/gst-plugins-good media-plugins/gst-plugins-jpeg media-plugins/gst-plugins-v4l2
-
-# Build tensorflow lite - legacy, can be used for debuging purposes
-# RUN cd .local && git clone https://github.com/tensorflow/tensorflow.git tensorflow_src
-# RUN cd .local/tensorflow_src && \
-#     PYTHON=python3.11 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh silvermont
-# RUN pip install /data/home/nao/.local/tensorflow_src/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist/tflite_runtime-2.16.0-cp311-cp311-linux_i686.whl
-
-#install tflite from wheel
-ADD wheels/tflite_runtime-2.16.0-cp311-cp311-linux_i686.whl /tmp/gentoo/tflite_runtime-2.16.0-cp311-cp311-linux_i686.whl
-RUN pip install /tmp/gentoo/tflite_runtime-2.16.0-cp311-cp311-linux_i686.whl && rm /tmp/gentoo/tflite_runtime-2.16.0-cp311-cp311-linux_i686.whl
-
-# Takes care of initializing the shell correctly
+# Shell initialization for NAO and Pepper
 COPY --chown=nao:nao config/.bash_profile /home/nao/.bash_profile
 
-# copy the content of scripts to ~/.local/share/scripts
+# Helper scripts
 COPY --chown=nao:nao scripts /home/nao/.local/share/scripts
 
-# RUN ls  /home/nao/.local
-# RUN cd .local && rm -rf vosk-api libqi libqi-python qibuild pybind11
-# # # # cleanup space first
-# RUN rm -rf /tmp/gentoo/var/cache/binpkgs/* /tmp/gentoo/var/tmp/* /home/nao/.cache/* /home/nao/gentoo/var/cache/distfiles/*
-# RUN cd / && rm -rf `find . -type d -name *.cache`
-# RUN cd / && rm -rf `find . -type d -name __pycache__`
-
-# # Hack to earn extra 500MB~
-# SHELL ["/bin/sh", "-c"]
-# USER root
-# # Remove all .git directories
-# RUN find /home/nao -name ".git" -type d -exec rm -rf {} \; || true
-# RUN rm -rf /opt
-# RUN du -sh /tmp/gentoo
-# USER nao
+# Cleanup build artifacts to minimize image footprint
+SHELL ["/bin/sh", "-c"]
+USER root
+RUN cd /home/nao/.local && rm -rf libqi libqi-python qibuild pybind11 2>/dev/null || true
+RUN rm -rf /tmp/gentoo/var/cache/binpkgs/* /tmp/gentoo/var/tmp/* /home/nao/.cache/* /home/nao/gentoo/var/cache/distfiles/* 2>/dev/null || true
+RUN find / -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
+RUN rm -rf /opt 2>/dev/null || true
+USER nao
 
 SHELL ["/tmp/gentoo/executeonprefix"]
 
-# RUN cd /home/nao && tar -c --lzma -f /tmp/pepper_os.tar.lzma -C /home/nao gentoo -C  /home/nao ros2_humble -C /home/nao .local -C /home/nao .bash_profile -C /home/nao naoqi -C /home/nao catkin_ros2 || true
+# Parallel LZMA compression with pxz
+# RUN cd /home/nao && tar -c --lzma -f /tmp/nao_os_jazzy.tar.lzma -C /home/nao gentoo -C /home/nao ros2_jazzy -C /home/nao .local -C /home/nao .bash_profile -C /home/nao naoqi -C /home/nao catkin_ros2 || true
 
 ENTRYPOINT ["/bin/bash"]
